name: Michael Paquier - Open source developer based in Japan
description: Blog about PostgreSQL and other things
url: http://michael.otacoo.com
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
permalink: /:categories/:title/
paginate: 10
paginate_path: page:num
tag_title_prefix: 'Posts tagged as &ldquo;'
tag_title_suffix: '&ldquo;'
tag_dir: 'tag'
